# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # Fedora 41 (Stable)

modules:
  # --- 1. Minimal Core Test ---
  # Installing ONLY safe packages to prove the build works
  - type: containerfile
    snippets:
      - RUN rpm-ostree install zsh starship

  # --- 2. Flatpaks ---
  - type: default-flatpaks
    notify: true
    system:
      - com.valvesoftware.Steam
      - dev.vencord.Vesktop

  # --- 3. System Services ---
  - type: systemd
    system:
      enabled:
        - podman.socket

  # --- 4. Scripts ---
  - type: script
    scripts:
      - post_install.sh
      # Sanity Check: Minimal Build
