# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # Fedora 43 (Stable)

modules:
  # --- 1. The Foundation (Files & Packages) ---
  - type: containerfile
    snippets:
      # Step A: Restore your custom files (Crucial for your "Dream Env")
      # Ensure you have moved your folders to 'recipes/configs' etc.
      - COPY recipes/configs /etc/skel/.config
      - COPY recipes/scripts /opt/lupineos/scripts
      - COPY recipes/assets /opt/lupineos/assets

      # Step B: Install ONLY the Safe Core Tools
      # Removed 'podman-docker' and 'distrobox' to prevent build conflicts.
      # You can install them inside the OS later if needed.
      - RUN rpm-ostree install \
          git \
          zsh \
          starship \
          stow \
          helix \
          neovim \
          eza \
          ripgrep \
          bat \
          zoxide \
          yazi \
          fzf \
          fd-find \
          tldr \
          fastfetch

  # --- 2. Flatpaks (Your Apps) ---
  - type: default-flatpaks
    notify: true
    system:
      # Gaming
      - com.valvesoftware.Steam
      - com.heroicgameslauncher.hgl
      - net.lutris.Lutris
      - net.davidotek.pupgui2
      # Social
      - dev.vencord.Vesktop
      # System Utils
      - com.github.tchx84.Flatseal
      - io.github.flattool.Warehouse
      - io.missioncenter.MissionCenter

  # --- 3. System Services ---
  - type: systemd
    system:
      enabled:
        - podman.socket

  # --- 4. Scripts ---
  - type: script
    scripts:
      - post_install.sh
      # Final Attempt: Safe Mode Build
