# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"

# --- BASE IMAGE: COSMIC ATOMIC ---
# we switch the base to the official Cosmic image so we don't need to rebase at runtime.
base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: 43

modules:
  # --- The "Raw Mode" Build ---
  - type: containerfile
    snippets:
      # Note: 'yazi' and 'eza' are removed (require COPR).
      
      # 1. Copy Payload (Your Configs, Assets, and the Autopilot Trigger)
      - COPY recipes/configs /etc/skel/.config
      - COPY recipes/scripts /opt/lupineos/scripts
      - COPY recipes/assets /opt/lupineos/assets

      # 2. Set Permissions (Make the bootstrap script executable)
      - RUN chmod +x /opt/lupineos/scripts/bootstrap.sh

      # 3. Enable Services (Replaces the broken 'systemd' module)
      - RUN systemctl enable podman.socket
