# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # Fedora 41 (Stable)

modules:
  # --- 1. Core Tools (Via Raw Command to bypass Builder Bug) ---
  - type: containerfile
    snippets:
      - RUN rpm-ostree install \
          git \
          zsh \
          starship \
          stow \
          helix \
          neovim \
          eza \
          ripgrep \
          bat \
          zoxide \
          fzf \
          fd-find \
          fastfetch

  # --- 2. Flatpaks (Your Apps) ---
  - type: default-flatpaks
    notify: true
    system:
      - com.valvesoftware.Steam
      - dev.vencord.Vesktop
      - io.missioncenter.MissionCenter

  # --- 3. System Services ---
  - type: systemd
    system:
      enabled:
        - podman.socket

  # --- 4. Scripts ---
  - type: script
    scripts:
      - post_install.sh
      # Final Fix: Silverblue Base + Raw Containerfile
