# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"

# --- BASE IMAGE: COSMIC ATOMIC ---
# Reverting to official base. We will FORCE ENABLE repos in the containerfile.
base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: 41

modules:
  # --- The "Raw Mode" Build ---
  - type: containerfile
    snippets:
      # 1. Copy Payload
      - COPY recipes/configs /etc/skel/.config
      - COPY recipes/etc /etc
      - COPY recipes/assets /opt/lupineos/assets
      - COPY recipes/scripts /opt/lupineos/scripts
      
      # 2. Run Native Install Script
      # This handles Repo Enabling + RPM Install + Binary Vending in a robust shell environment.
      - RUN chmod +x /opt/lupineos/scripts/*.sh && /opt/lupineos/scripts/native_install.sh
      
      # 5. Copy Branding & Systemd
      # Wallpapers & Plymouth
      - COPY recipes/assets/wallpapers /usr/share/backgrounds/lupineos
      - COPY recipes/assets/plymouth/lupineos /usr/share/plymouth/themes/lupineos
      - RUN plymouth-set-default-theme lupineos
      
      # Welcome App (Example placeholder)
      - COPY recipes/bin/lupineos-welcome /usr/bin/lupineos-welcome

      # Systemd Units
      - COPY recipes/assets/systemd/lupineos-firstboot.service /usr/lib/systemd/system/lupineos-firstboot.service

      # 7. Autostart (First Login Welcome)
      - COPY recipes/assets/autostart /etc/xdg/autostart

      # 6. Enable Services
      - RUN systemctl enable podman.socket
      - RUN systemctl enable lupineos-firstboot.service
