# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"

# --- BASE IMAGE: COSMIC ATOMIC ---
# we switch the base to the official Cosmic image so we don't need to rebase at runtime.
base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: 43

modules:
  # --- The "Raw Mode" Build ---
  - type: containerfile
    snippets:
      # We override the base tree with our custom package set.
      # Note: 'yazi' and 'eza' are removed (require COPR).
      # 'tldr' -> 'tealdeer', 'task' -> 'taskwarrior', 'fd' -> 'fd-find'.
      - RUN rpm-ostree install -y \
          git zsh util-linux-user starship stow \
          helix neovim ripgrep bat zoxide \
          fzf fd-find tealdeer fastfetch \
          distrobox taskwarrior

      # 2. Copy Configs (The Senses)
      - COPY recipes/configs /etc/skel/.config
      - COPY recipes/assets /opt/lupineos/assets

      # 3. Enable System Services
      - RUN systemctl enable podman.socket
