# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"

# --- BASE IMAGE: COSMIC ATOMIC (uBlue) ---
# We switch to Universal Blue because it has better repo support for layering.
# The official fedora-ostree-desktops image was missing standard repos.
base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: latest  # '41' tag does not exist for this image, usage 'latest'

modules:
  # --- The "Raw Mode" Build ---
  - type: containerfile
    snippets:
      # 1. Enable Community Repos (COPR)
      # We download the repos and explicitly DISABLE gpgcheck to avoid build failures.
      # flattened to single lines to prevent YAML/Shell escaping issues (double backslash error)
      - RUN curl -L -o /etc/yum.repos.d/atim-starship.repo https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-43/atim-starship-fedora-43.repo && sed -i 's/gpgcheck=1/gpgcheck=0/g' /etc/yum.repos.d/atim-starship.repo
      - RUN curl -L -o /etc/yum.repos.d/alternateved-eza.repo https://copr.fedorainfracloud.org/coprs/alternateved/eza/repo/fedora-43/alternateved-eza-fedora-43.repo && sed -i 's/gpgcheck=1/gpgcheck=0/g' /etc/yum.repos.d/alternateved-eza.repo
      - RUN curl -L -o /etc/yum.repos.d/varlad-yazi.repo https://copr.fedorainfracloud.org/coprs/varlad/yazi/repo/fedora-43/varlad-yazi-fedora-43.repo && sed -i 's/gpgcheck=1/gpgcheck=0/g' /etc/yum.repos.d/varlad-yazi.repo

      # 2. Install Fedora Core Tools (Stable)
      - RUN rpm-ostree install -y \
          git zsh util-linux-user stow \
          helix neovim ripgrep bat zoxide \
          fzf fd-find tealdeer fastfetch \
          distrobox taskwarrior

      # 3. Install Bleeding Edge Tools (COPR)
      - RUN rpm-ostree install -y \
          starship \
          eza \
          yazi

      # 4. Copy Configs & Assets
      - COPY recipes/configs /etc/skel/.config
      - COPY recipes/assets /opt/lupineos/assets
      
      # 5. Copy Branding & Systemd (From other agent's work)
      # Wallpapers & Plymouth
      - COPY recipes/assets/wallpapers /usr/share/backgrounds/lupineos
      - COPY recipes/assets/plymouth/lupineos /usr/share/plymouth/themes/lupineos
      - RUN plymouth-set-default-theme -R lupineos
      
      # Welcome App (Example placeholder)
      # - COPY recipes/bin/lupineos-welcome /usr/bin/lupineos-welcome

      # Systemd Units
      - COPY recipes/assets/systemd/lupineos-firstboot.service /usr/lib/systemd/system/lupineos-firstboot.service

      # 6. Enable Services
      - RUN systemctl enable podman.socket
      - RUN systemctl enable lupineos-firstboot.service
