# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # Matches current Fedora Stable

modules:
  # --- 1. System Packages (The "Direct Order" Fix) ---
  - type: containerfile
    snippets:
      - RUN rpm-ostree install \
          git \
          zsh \
          util-linux-user \
          starship \
          stow \
          helix \
          neovim \
          eza \
          ripgrep \
          bat \
          zoxide \
          yazi \
          fzf \
          fd-find \
          tldr \
          fastfetch \
          distrobox \
          podman-docker

  # --- 2. Flatpaks ---
  - type: default-flatpaks
    notify: true
    system:
      # Gaming
      - com.valvesoftware.Steam
      - com.heroicgameslauncher.hgl
      - net.lutris.Lutris
      - net.davidotek.pupgui2         # ProtonUp-Qt
      # Social
      - dev.vencord.Vesktop           # Discord
      # System Utils
      - com.github.tchx84.Flatseal    # Permission manager
      - io.github.flattool.Warehouse  # Flatpak manager
      - io.missioncenter.MissionCenter # System Monitor

  # --- 3. System Services ---
  - type: systemd
    system:
      enabled:
        - podman.socket

  # --- 4. Scripts ---
  - type: script
    scripts:
      - post_install.sh
      # Force cache clear update 3
