# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # Fedora 43 (Stable)

modules:
  # --- The "Raw Mode" Build ---
  # We are using ONLY 'containerfile' snippets.
  # This bypasses ALL BlueBuild modules to avoid the "unbound variable" bug.
  - type: containerfile
    snippets:
      # 1. Copy Payload (Your Configs, Assets, and the Autopilot Trigger)
      - COPY recipes/configs /etc/skel/.config
      - COPY recipes/scripts /opt/lupineos/scripts
      - COPY recipes/assets /opt/lupineos/assets

      # 2. Set Permissions (Make the bootstrap script executable)
      - RUN chmod +x /opt/lupineos/scripts/bootstrap.sh

      # 3. Enable Services (Replaces the broken 'systemd' module)
      - RUN systemctl enable podman.socket
