# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # Fedora 43 (Stable)

modules:
  # --- The Payload (Files ONLY) ---
  # We strictly COPY files. We do not run installs. We do not enable services.
  # This avoids 100% of the errors we have seen.
  - type: containerfile
    snippets:
      - COPY recipes/configs /etc/skel/.config
      - COPY recipes/scripts /opt/lupineos/scripts
      - COPY recipes/assets /opt/lupineos/assets
