# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # Fedora 43 (Stable)

modules:
  # --- 1. The Foundation (Files & Packages) ---
  - type: containerfile
    snippets:
      # Step A: Restore your custom files (Crucial for your "Dream Env")
      # This saves your configs/scripts into the image.
      - COPY recipes/configs /etc/skel/.config
      - COPY recipes/scripts /opt/lupineos/scripts
      - COPY recipes/assets /opt/lupineos/assets

      # Step B: Install ONLY Safe Core Tools
      # We removed yazi, eza, fastfetch, and bat to prevent "Package Not Found" errors.
      # You will install these easily after booting.
      - RUN rpm-ostree install \
          git \
          zsh \
          starship \
          stow \
          neovim \
          ripgrep \
          fzf \
          fd-find \
          zoxide

  # --- 2. Flatpaks (Your Apps) ---
  - type: default-flatpaks
    notify: true
    system:
      # Gaming
      - com.valvesoftware.Steam
      - com.heroicgameslauncher.hgl
      - net.lutris.Lutris
      - net.davidotek.pupgui2
      # Social
      - dev.vencord.Vesktop
      # System Utils
      - com.github.tchx84.Flatseal
      - io.github.flattool.Warehouse
      - io.missioncenter.MissionCenter

  # --- 3. System Services ---
  - type: systemd
    system:
      enabled:
        - podman.socket

  # --- 4. Scripts ---
  - type: script
    scripts:
      - post_install.sh
      # Final Attempt: Lifeboat Build
