# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # Fedora 41 (Stable)

modules:
  # Intentionally Empty
  # We are building the pure base image to bypass CI errors.
