# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # Fedora 41 (Stable)

modules:
  # --- 1. Core Tools (Simplified) ---
  # We use the native 'rpm-ostree' module which is safer than raw containerfile commands
  - type: rpm-ostree
    install:
      # Shell & Core
      - git
      - zsh
      - starship
      - stow
      # Editors
      - helix
      - neovim
      # CLI Power Tools
      - eza
      - ripgrep
      - bat
      - zoxide
      - fzf
      - fd-find
      - fastfetch
      # - yazi  <-- Temporarily removed (often causes repo issues, we add back next)
      # - distrobox <-- Built-in to Silverblue now
      # - podman-docker <-- Built-in or conflicts

  # --- 2. Flatpaks (Your Apps) ---
  - type: default-flatpaks
    notify: true
    system:
      - com.valvesoftware.Steam
      - dev.vencord.Vesktop
      - io.missioncenter.MissionCenter

  # --- 3. System Services ---
  - type: systemd
    system:
      enabled:
        - podman.socket

  # --- 4. Scripts ---
  - type: script
    scripts:
      - post_install.sh
      # Force Reset: Sanity Check Build 1
