# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"
# We switch to Silverblue because it is the Official Stable image for Fedora 43.
# The 'Cosmic' specific image is currently missing/broken in the custom builder.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # Fedora 43 (Current Stable)

modules:
  # --- 1. The Foundation (Files & Packages) ---
  # 'containerfile' bypasses the BlueBuild bugs by using raw Docker commands.
  - type: containerfile
    snippets:
      # Step A: Restore your custom files
      - COPY recipes/configs /etc/skel/.config
      - COPY recipes/scripts /opt/lupineos/scripts
      - COPY recipes/assets /opt/lupineos/assets

      # Step B: Install ALL requested tools
      # We use 'RUN' to force installation. This list includes Distrobox (better Toolbx).
      - RUN rpm-ostree install \
          git \
          zsh \
          util-linux-user \
          starship \
          stow \
          helix \
          neovim \
          eza \
          ripgrep \
          bat \
          zoxide \
          yazi \
          fzf \
          fd-find \
          tldr \
          fastfetch \
          distrobox \
          podman-docker

  # --- 2. Flatpaks (Your Apps) ---
  - type: default-flatpaks
    notify: true
    system:
      # Gaming
      - com.valvesoftware.Steam
      - com.heroicgameslauncher.hgl
      - net.lutris.Lutris
      - net.davidotek.pupgui2
      # Social
      - dev.vencord.Vesktop
      # System Utils
      - com.github.tchx84.Flatseal
      - io.github.flattool.Warehouse
      - io.missioncenter.MissionCenter

  # --- 3. System Services ---
  - type: systemd
    system:
      enabled:
        - podman.socket

  # --- 4. Scripts ---
  - type: script
    scripts:
      - post_install.sh
      # Final Build: Fedora 43 Silverblue + Full Config
