# config/recipe.yml
name: lupineos
description: "The WolfPack - Custom Fedora Atomic Workstation"

# --- BASE IMAGE: COSMIC ATOMIC ---
# we switch the base to the official Cosmic image so we don't need to rebase at runtime.
base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: 43

modules:
  # --- The "Raw Mode" Build ---
  - type: containerfile
    snippets:
      # Note: 'yazi' and 'eza' are removed (require COPR).
      
      # 1. Enable Community Repos (COPR)
      - RUN curl -L -o /etc/yum.repos.d/atim-starship.repo https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-43/atim-starship-fedora-43.repo
      - RUN curl -L -o /etc/yum.repos.d/alternateved-eza.repo https://copr.fedorainfracloud.org/coprs/alternateved/eza/repo/fedora-43/alternateved-eza-fedora-43.repo
      - RUN curl -L -o /etc/yum.repos.d/varlad-yazi.repo https://copr.fedorainfracloud.org/coprs/varlad/yazi/repo/fedora-43/varlad-yazi-fedora-43.repo

      # 2. Install All Tools (The Pack)
      - RUN rpm-ostree install -y \
          git zsh util-linux-user starship stow \
          helix neovim eza ripgrep bat zoxide \
          yazi fzf fd-find tealdeer fastfetch \
          distrobox taskwarrior

      # 1. Copy Payload (Your Configs, Assets, and the Autopilot Trigger)
      - COPY recipes/configs /etc/skel/.config
      - COPY recipes/scripts /opt/lupineos/scripts
      - COPY recipes/assets /opt/lupineos/assets
      
      # Copy Wallpapers
      - COPY recipes/assets/wallpapers /usr/share/backgrounds/lupineos

      # Copy Plymouth Theme
      - COPY recipes/assets/plymouth/lupineos /usr/share/plymouth/themes/lupineos
      - RUN plymouth-set-default-theme -R lupineos

      # Copy Welcome App (Assuming it's built and placed in recipes/bin by a pre-script or we copy from sandbox if local build works)
      # For now, let's assume we copy the binary from a local 'recipes/bin' folder we will create
      - COPY recipes/bin/lupineos-welcome /usr/bin/lupineos-welcome

      # Copy Systemd Units
      - COPY recipes/assets/systemd/lupineos-firstboot.service /usr/lib/systemd/system/lupineos-firstboot.service

      # 2. Set Permissions (Make the bootstrap script executable)
      - RUN chmod +x /opt/lupineos/scripts/bootstrap.sh
      - RUN chmod +x /opt/lupineos/scripts/lupineos-firstboot.sh
      - RUN chmod +x /usr/bin/lupineos-welcome

      # 3. Enable Services (Replaces the broken 'systemd' module)
      - RUN systemctl enable podman.socket
      - RUN systemctl enable lupineos-firstboot.service
